self-hosted-runner:
  labels:
    - retaillens-wack
    - interactive
    - elevated
    - retaillens-release-build
    - retaillens-release-signing
    - retaillens-release-publisher
    - ephemeral
    - no-checkout
